version: "3.4"

services:
  waqs:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default:
        ipv4_address: 170.50.0.10
    ports:
      - 12345:12345
    restart: always
    entrypoint: "/usr/bin/nohup socat -d -d -s -t 60 -T 60 TCP4-LISTEN:12345,fork,reuseaddr EXEC:/WAQS"

  db:
    image: postgres:12.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: debug
      POSTGRES_DB: air_quality_db
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./db-dir:/var/lib/postgresql/data

networks:
  default:
    ipam:
      config:
        - subnet: 170.50.0.0/16
