version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    # ports:
    #   - 5000:5000
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443