version: '3'

services:
    ctf:
        restart: always
        build: ./
        read_only: true
        networks:
            - internal
networks:
    default:
    internal:
        internal: true
