version: '3'
services:
  safari_park:
    build:
      context: .
    working_dir: /home/pwn
    container_name: safari_park
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9004:9004"
    entrypoint: /etc/init.sh
